# Generated by Django 6.0.7 on 2026-07-25 06:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "output_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Processing results such as preview paths, extracted metadata, etc.",
                    ),
                ),
                (
                    "survey_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_job",
                        to="uploads.surveyfile",
                    ),
                ),
            ],
            options={
                "db_table": "processing_processing_job",
                "ordering": ["-created_at"],
            },
        ),
    ]
