# Generated by Django 6.0.7 on 2026-07-25 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project"], name="accounts_pr_project_b3da22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["user"], name="accounts_pr_user_id_5e23d0_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["role"], name="accounts_pr_role_42e32f_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "user"], name="accounts_pr_project_5b6219_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_project_membership"
            ),
        ),
    ]
