# Generated by Django 6.0.7 on 2026-07-25 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SURVEY_CREATED", "Survey Created"),
                            ("FILE_UPLOADED", "File Uploaded"),
                            ("FILE_UPLOAD_FAILED", "File Upload Failed"),
                            ("PROCESSING_STARTED", "Processing Started"),
                            ("PROCESSING_FAILED", "Processing Failed"),
                            ("PROCESSING_RETRIED", "Processing Retried"),
                            ("SURVEY_APPROVED", "Survey Approved"),
                            ("SURVEY_REJECTED", "Survey Rejected"),
                            ("SURVEY_ARCHIVED", "Survey Archived"),
                            ("FILE_DOWNLOADED", "File Downloaded"),
                            ("MEASUREMENT_CREATED", "Measurement Created"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="audit_audit_action_e47115_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_77a657_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_audit_created_a57734_idx"
                    ),
                ],
            },
        ),
    ]
