# Generated by Django 6.0.7 on 2026-07-25 06:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable survey name.", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("survey_date", models.DateField(db_index=True)),
                ("drone_model", models.CharField(max_length=255)),
                (
                    "pilot",
                    models.CharField(
                        help_text="Name of the drone pilot.", max_length=255
                    ),
                ),
                (
                    "coordinate_reference_system",
                    models.CharField(
                        help_text="Coordinate Reference System (e.g. EPSG:4326).",
                        max_length=50,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        geography=True,
                        help_text="Survey coverage boundary.",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UPLOADING", "Uploading"),
                            ("READY", "Ready"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="projects.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="projects.site",
                    ),
                ),
            ],
            options={
                "db_table": "surveys_survey",
                "ordering": ["-survey_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measurement_type",
                    models.CharField(
                        choices=[("DISTANCE", "Distance"), ("AREA", "Area")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Optional user-defined label for the measurement.",
                        max_length=255,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Calculated distance or area value.",
                        max_digits=18,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Example: m, km, m², hectares.", max_length=20
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "surveys_measurement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["project"], name="surveys_sur_project_7c6f3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["site"], name="surveys_sur_site_id_1c1415_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["status"], name="surveys_sur_status_88f57b_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["processing_status"], name="surveys_sur_process_91c08d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["survey_date"], name="surveys_sur_survey__707247_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.UniqueConstraint(
                fields=("site", "survey_date"), name="unique_site_survey_date"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["survey"], name="surveys_mea_survey__53aa46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["measurement_type"], name="surveys_mea_measure_014e1d_idx"
            ),
        ),
    ]
