# Generated by Django 6.0.7 on 2026-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="model_directory",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="survey",
            name="tile_directory",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
