# Generated by Django 6.0.7 on 2026-07-25 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to="surveys.survey",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uploads_upload_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_file", models.FileField(upload_to="surveys/original/")),
                (
                    "converted_file",
                    models.FileField(
                        blank=True, null=True, upload_to="surveys/converted/"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="surveys/previews/"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_filename", models.CharField(max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("ORTHOMOSAIC", "Orthomosaic"),
                            ("POINT_CLOUD", "Point Cloud"),
                            ("MODEL", "3D Model"),
                            ("MESH", "Mesh"),
                            ("KML", "KML"),
                            ("GEOJSON", "GeoJSON"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("extension", models.CharField(max_length=20)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                (
                    "checksum",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 checksum for duplicate detection.",
                        max_length=64,
                    ),
                ),
                ("validation_passed", models.BooleanField(default=False)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Extracted file metadata."
                    ),
                ),
                (
                    "parent_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent file for grouped uploads (e.g. OBJ -> MTL -> textures).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_files",
                        to="uploads.surveyfile",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="surveys.survey",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="uploads.uploadsession",
                    ),
                ),
            ],
            options={
                "db_table": "uploads_survey_file",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["survey"], name="uploads_sur_survey__5f7e39_idx"
                    ),
                    models.Index(
                        fields=["upload_session"], name="uploads_sur_upload__c220d9_idx"
                    ),
                    models.Index(
                        fields=["checksum"], name="uploads_sur_checksu_d706fb_idx"
                    ),
                    models.Index(
                        fields=["file_format"], name="uploads_sur_file_fo_f9a966_idx"
                    ),
                ],
            },
        ),
    ]
