# Generated by Django 6.0.7 on 2026-07-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyfile",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="surveyfile",
            name="parent_file",
        ),
        migrations.RemoveField(
            model_name="surveyfile",
            name="stored_filename",
        ),
        migrations.AddField(
            model_name="surveyfile",
            name="relative_path",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="processing_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="upload_type",
            field=models.CharField(
                choices=[("2D", "2D Deliverables"), ("3D", "3D Deliverables")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
