# Generated by Django 6.0.7 on 2026-07-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0002_remove_surveyfile_extension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="current_step",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="surveyfile",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("ORTHOMOSAIC", "Orthomosaic"),
                    ("DSM", "Digital Surface Model"),
                    ("DTM", "Digital Terrain Model"),
                    ("POINT_CLOUD", "Point Cloud"),
                    ("MODEL", "3D Model"),
                    ("MESH", "Mesh"),
                    ("KML", "KML"),
                    ("GEOJSON", "GeoJSON"),
                    ("METADATA", "Metadata"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="uploadsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PROCESSING",
                max_length=20,
            ),
        ),
    ]
