# Generated by Django 6.0.7 on 2026-07-27 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0003_uploadsession_current_step_uploadsession_progress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsession",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="uploadsession",
            name="upload_type",
        ),
    ]
