# Generated by Django 6.0.7 on 2026-07-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0004_remove_uploadsession_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="archive",
            field=models.FileField(default=1, upload_to="survey_uploads/"),
            preserve_default=False,
        ),
    ]
