# Generated by Django 6.0.7 on 2026-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0005_uploadsession_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyfile",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="surveyfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="surveyfile",
            name="tile_bounds",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyfile",
            name="tile_directory",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
