# Generated by Django 6.0.7 on 2026-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_surveyfile_error_message_surveyfile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfile',
            name='model_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='surveyfile',
            name='point_cloud_directory',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='processed_files',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='total_files',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('COMPLETED_WITH_ERRORS', 'Completed with errors')], db_index=True, default='PROCESSING', max_length=50),
        ),
    ]
